apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: gitlab-scaffolding
  namespace: gitlab-system
spec:
  chart:
    repo: gitlab-scaffolding
    url: https://charts.krateo.io
    version: 0.1.0