apiVersion: v1
data:
  drawer: "true"
  form: "true"
  showFormStructure: "true"
  drawerSize: large
kind: ConfigMap
metadata:
  name: template-fireworksapp-card
  namespace: fireworksapp-system
---
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: template-fireworksapp-card
  namespace: fireworksapp-system
spec:
  actions:
  - template:
      apiVersion: templates.krateo.io/v1alpha1
      name: template-fireworksapp-form
      namespace: fireworksapp-system
      resource: forms
      verb: GET
  - template:
      apiVersion: core.krateo.io/v1alpha1
      name: fireworksapp
      namespace: fireworksapp-system
      resource: compositiondefinitions
      verb: DELETE
  app:
    template:
      color: ${ .getCompositionDefinition.status.conditions[] | select(.type == "Ready") | if .status == "False" then "orange" elif .status == "True" then "green" else "grey" end }
      content: This is a card for FireworksApp template (classic form)
      icon: fa-cubes
      tags: fireworksapp-system,1.1.13
      title: FireworksApp
      status: ${ .getCompositionDefinition.status.conditions[] | select(.type == "Ready") | "Ready:" + .status }
      date: ${ .getCompositionDefinition.metadata.creationTimestamp }
  propsRef:
    name: template-fireworksapp-card
    namespace: fireworksapp-system
  type: card
  api:
  - name: getCompositionDefinition
    path: "/apis/core.krateo.io/v1alpha1/namespaces/fireworksapp-system/compositiondefinitions/fireworksapp"
    verb: GET
    headers:
    - 'Accept: application/json'
---
apiVersion: templates.krateo.io/v1alpha1
kind: Form
metadata:
  name: template-fireworksapp-form
  namespace: fireworksapp-system
spec:
  compositionDefinitionRef:
    name: fireworksapp
    namespace: fireworksapp-system