apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "fireworks-app.fullname" . }}
  labels:
    {{- include "fireworks-app.labels" . | nindent 4 }}
spec:
  project: {{ .Values.argocd.project | default "default" }}
  source:
    repoURL: {{ .Values.argocd.source.repoURL }}
    targetRevision: {{ .Values.argocd.source.targetRevision }}
    path: {{ .Values.argocd.source.path }}
  destination:
    server: {{ .Values.argocd.destination.server }}
    namespace: {{ .Values.argocd.destination.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.argocd.syncPolicy.automated.prune }}
      selfHeal:
    syncOptions: 
    {{- range .Values.argocd.syncPolicy.syncOptions }}
      - {{ . }}
    {{- end }}