apiVersion: github.krateo.io/v1alpha1
kind: Repo
metadata:
  name: {{ include "fireworks-app.fullname" . }}-repo
  labels:
    {{- include "fireworks-app.labels" . | nindent 4 }}
  annotations:
    krateo.io/connector-verbose: "{{ .Values.git.toRepo.verbose }}"
    krateo.io/deletion-policy: {{ .Values.git.toRepo.deletionPolicy }}
spec:
  authenticationRefs:
    bearerAuthRef: bearer-github-ref
  org: {{ .Values.git.toRepo.org }}
  name: {{ .Values.git.toRepo.name }}
  private: {{ .Values.git.toRepo.private }}
  auto_init: {{ .Values.git.toRepo.initialize }}
