apiVersion: github.krateo.io/v1alpha1
kind: ProviderConfig
metadata:
  name: {{ include "fireworks-app.fullname" . }}-repo-providerconfig
  labels:
    {{- include "fireworks-app.labels" . | nindent 4 }}
spec:
  apiUrl: {{ .Values.git.toRepo.apiUrl }}
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Values.git.toRepo.credentials.secretRef.namespace }}
      name: {{ .Values.git.toRepo.credentials.secretRef.name }}
      key: {{ .Values.git.toRepo.credentials.secretRef.key }}