apiVersion: git.krateo.io/v1alpha1
kind: Repo
metadata:
  name: {{ include "fireworks-app.fullname" . }}-repo
  labels:
    {{- include "fireworks-app.labels" . | nindent 4 }}
spec:
  providerConfigRef:
    name: {{ include "fireworks-app.fullname" . }}-repo-providerconfig
  deletionPolicy: {{ .Values.git.deletionPolicy }}
  forProvider:
    fromRepo:
      url: {{ .Values.git.fromRepo.url }}
      path: {{ .Values.git.fromRepo.path }}
    toRepo:
      url: {{ include "fireworks-app.toRepoUrl" . }}
      path: {{ .Values.git.toRepo.path }}
    configMapKeyRef:
      namespace: {{ .Release.Namespace }}
      name: {{ include "fireworks-app.fullname" . }}-replace-values
      key: values
