apiVersion: git.krateo.io/v1alpha1
kind: Repo
metadata:
  name: {{ include "gitlab-scaffolding.fullname" . }}-repo
  labels:
    {{- include "gitlab-scaffolding.labels" . | nindent 4 }}
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  unsupportedCapabilities: {{ .Values.git.unsupportedCapabilities }}
  insecure: {{ .Values.git.insecure }}
  deletionPolicy: {{ .Values.git.deletionPolicy }}
  configMapKeyRef:
    namespace: {{ .Release.Namespace }}
    name: {{ include "gitlab-scaffolding.fullname" . }}-replace-values
    key: values
  fromRepo:
    url: https://gitlab.com/ldepandis/{{ .Values.git.fromRepo.name }}
    branch: {{ .Values.git.fromRepo.branch }}
    authMethod: {{ .Values.git.fromRepo.credentials.authMethod }}
    path: {{ .Values.git.fromRepo.path }}
    secretRef:
      namespace: {{ .Values.git.fromRepo.credentials.secretRef.namespace }}
      name: {{ .Values.git.fromRepo.credentials.secretRef.name }}
      key: {{ .Values.git.fromRepo.credentials.secretRef.key }}
  toRepo:
    url: https://gitlab.com/ldepandis/{{ .Values.git.toRepo.name }}
    branch: {{ .Values.git.toRepo.branch }}
    authMethod: {{ .Values.git.toRepo.credentials.authMethod }}
    secretRef:
      namespace: {{ .Values.git.toRepo.credentials.secretRef.namespace }}
      name: {{ .Values.git.toRepo.credentials.secretRef.name }}
      key: {{ .Values.git.toRepo.credentials.secretRef.key }}