kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: fireworksapp-template-panel-schema-ordered
  namespace: fireworksapp-system
  labels:
    krateo.io/portal-page: templates
spec:
  apiRef:
    name: fireworksapp-compositiondefinition
    namespace: fireworksapp-system
  widgetData:
    clickActionId: template-click-action
    footer:
      - resourceRefId: template-panel-button
    tags:
      - fireworksapp-system
      - 2.0.2
    icon:
      name: fa-solid fa-cubes
    items:
      - resourceRefId: template-panel-paragraph
    title: FireworksApp (Ordered Schema)
    actions:
      openDrawer:
        - id: template-click-action
          resourceRefId: template-form
          type: openDrawer
          size: large
          title: Fireworksapp (Ordered)
  widgetDataTemplate:
    - forPath: icon.color
      expression: ${ ((.getCompositionDefinition?.status?.conditions // []) | map(select(.type == "Ready") | if .status == "False" then "orange" elif .status == "True" then "green" else "grey" end) | first) // "grey" }
    - forPath: headerLeft
      expression: ${ ((.getCompositionDefinition?.status?.conditions // []) | map(select(.type == "Ready") | if .status == "False" then "Ready:False" elif .status == "True" then "Ready:True" else "Ready:Unknown" end) | first) // "Ready:Unknown" }
    - forPath: headerRight
      expression: ${ .getCompositionDefinition // {} | .metadata.creationTimestamp // "In the process of being created" }
  resourcesRefs:
    - id: template-panel-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: fireworksapp-template-panel-paragraph-schema-ordered
      namespace: fireworksapp-system
      resource: paragraphs
      verb: GET
    - id: template-panel-button
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: fireworksapp-template-panel-button-schema-ordered
      namespace: fireworksapp-system
      resource: buttons
      verb: GET
    - id: template-form
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: fireworksapp-form-ordered
      namespace: fireworksapp-system
      resource: forms
      verb: GET