name: ci-docker

on:
  push:
    branches:
      - "**"
env:
  REGISTRY: ghcr.io
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Res
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get short SHA
        id: slug
        # run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        run: echo "SHA8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> "$GITHUB_ENV"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:app"
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' && true || false }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.SHA8 }}
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
