name: test-release

on:
  pull_request:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract Version
        id: tagger
        uses: battila7/get-version-action@v2

      - name: Print Version
        run: |
          echo ${{steps.tagger.outputs.version}}
          echo ${{steps.tagger.outputs.version-without-v}}

      - name: Replace Version in Chart.yaml
        run: sed -i 's/CHART_VERSION/${{ steps.tagger.outputs.version-without-v }}/g' ./chart/Chart.yaml

      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0

      - name: Helm lint
        run: helm lint ./chart
